rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'CI (macos-latest, 3.0, spec)'
    - 'CI (ubuntu-latest, 2.6, spec)'
    - 'CI (ubuntu-latest, 2.7, spec)'
    - 'CI (ubuntu-latest, 3.0, rubocop , build , yardoc , linkinator)'
    - 'CI (ubuntu-latest, 3.0, spec)'
    - 'CI (ubuntu-latest, 3.1, spec)'
    - 'CI (windows-latest, 3.0, spec)'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-ruby-admins
    permission: admin
  - team: yoshi-ruby
    permission: push
